// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc2xvDuxVBcGTHn18ILj_czlJEXdWUCk4',
    appId: '1:649547857974:web:15788e4a964850b84dd897',
    messagingSenderId: '649547857974',
    projectId: 'social-media-3c719',
    authDomain: 'social-media-3c719.firebaseapp.com',
    storageBucket: 'social-media-3c719.appspot.com',
    measurementId: 'G-9CH2VR3LFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsaSiBHwHBEhaefHbXqMme6tOgJnQhTQg',
    appId: '1:649547857974:android:6134aa0e514567e04dd897',
    messagingSenderId: '649547857974',
    projectId: 'social-media-3c719',
    storageBucket: 'social-media-3c719.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXvwO1kKV5LS1hOCJ_nDgZYL_GntcVRs',
    appId: '1:649547857974:ios:c24ac052357addc54dd897',
    messagingSenderId: '649547857974',
    projectId: 'social-media-3c719',
    storageBucket: 'social-media-3c719.appspot.com',
    iosBundleId: 'com.example.postingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfXvwO1kKV5LS1hOCJ_nDgZYL_GntcVRs',
    appId: '1:649547857974:ios:c24ac052357addc54dd897',
    messagingSenderId: '649547857974',
    projectId: 'social-media-3c719',
    storageBucket: 'social-media-3c719.appspot.com',
    iosBundleId: 'com.example.postingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc2xvDuxVBcGTHn18ILj_czlJEXdWUCk4',
    appId: '1:649547857974:web:5b58513d77342f6d4dd897',
    messagingSenderId: '649547857974',
    projectId: 'social-media-3c719',
    authDomain: 'social-media-3c719.firebaseapp.com',
    storageBucket: 'social-media-3c719.appspot.com',
    measurementId: 'G-J58549BG15',
  );
}
